name: DynamicDeploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build app.
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn run build
      - name: Serverless deploy.
        uses: serverless/github-action@master
        with:
          args: -c "serverless plugin install --name serverless-finch && serverless client deploy --branch=${GITHUB_REF##*/} --verbose"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
