name: 'Clean up dynamic provisioned resources.'

on: 
  delete

jobs:
  clean:
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Destroy app.
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn run build
      - run: yarn global add serverless
      - run: npx serverless client remove --branch=${{ github.event.ref }} --no-confirm
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  