name: 'Clean up resources provisioned for PR'

on: 
  delete

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: export BRANCH=$(git branch --show-current)
      - run: env