name: DynamicDeploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  github-actions-environment-variables-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: List of the GitHub Actions environment variables on Windows
        run: env
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build app.
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: yarn install
      - run: yarn run build
      - run: yarn global add serverless
      - run: npx serverless client deploy --branch=${GITHUB_REF##*/} --no-confirm
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
